import React from 'react';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/styles/globals.css';
import AsyncBoundary from '@/components/common/AsyncBoundary';
import ModalProvider from '@/libs/contexts/ModalProvider';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <AsyncBoundary>
          <ModalProvider>{children}</ModalProvider>
        </AsyncBoundary>
        <div id="modal-root" />
      </body>
    </html>
  );
}
