import React from 'react';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import ReactQueryProvider from '@/apis/components/ReactQueryProvider';
import KakaoScript from '@/components/social/KaKaoScript';
import 'react-day-picker/dist/style.css';
import '@/styles/globals.css';
import { PasswordFindProvider } from '@/libs/contexts/passwordFindContext';

declare global {
  interface Window {
    Kakao: any;
  }
}
const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <PasswordFindProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </PasswordFindProvider>
        <KakaoScript />
      </body>
    </html>
  );
}
