import React from 'react';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import KakaoScript from '../../KaKaoScript';

import '@/styles/globals.css';

declare global {
  interface Window {
    Kakao: any;
  }
}
const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>{children}</body>
      <KakaoScript />
    </html>
  );
}
